export const LOCALIZATION_FALLBACK_GAP_MARKER = 'fallback_allowed_until_resource_editor';

export const LOCALIZATION_FALLBACK_GAP_POLICY = Object.freeze({
  marker: LOCALIZATION_FALLBACK_GAP_MARKER,
  owner: 'admin_localization_resource_editor',
  source: 'admin_localization_resources_editor',
  rationale: 'Non-English app translations are supplied through the admin localization resource editor; English resources remain the runtime fallback until locale resources are completed.',
  locales: Object.freeze([
    'am',
    'ar',
    'bn',
    'de',
    'es',
    'fa',
    'fr',
    'ha',
    'hi',
    'it',
    'ja',
    'jv',
    'ko',
    'my',
    'pa',
    'ps',
    'pt',
    'ru',
    'sgd',
    'so',
    'th',
    'tl',
    'tr',
    'uk',
    'uz',
    'vi',
    'zh',
  ]),
  namespaces: Object.freeze([
    'administration',
    'appointment_config',
    'appointment_settings',
    'auth',
    'calendar',
    'calls',
    'chat_archive',
    'common',
    'errors',
    'governance',
    'infrastructure',
    'localization',
    'marketplace',
    'navigation',
    'onboarding',
    'page',
    'pagination',
    'public',
    'settings',
    'tenant',
    'theme_editor',
    'theme_preview',
    'theme_settings',
    'users',
  ]),
});
