#!/bin/bash
# help.sh - Help script for the King PHP extension

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${GREEN}King PHP Extension - Build System Help${NC}"
echo ""
echo -e "${YELLOW}Available Make Targets:${NC}"
echo ""
echo -e "${BLUE}build${NC}      - Build the King extension and all dependencies"
echo -e "${BLUE}unit${NC}       - Run unit tests"
echo -e "${BLUE}fuzz${NC}       - Run canonical fuzz, stress, and edge-case tests"
echo -e "${BLUE}stub-parity${NC} - Verify public PHP stubs against the live runtime"
echo -e "${BLUE}go-live-readiness${NC} - Run the final repo-local go-live readiness gate"
echo -e "${BLUE}release-package${NC} - Build the canonical reproducible release package"
echo -e "${BLUE}release-package-verify${NC} - Verify package reproducibility and emit the release tarball"
echo -e "${BLUE}clean${NC}      - Clean all build artifacts"
echo -e "${BLUE}tree${NC}       - Show project directory tree"
echo -e "${BLUE}ext-tree${NC}   - Show extension directory tree"
echo -e "${BLUE}infra-tree${NC} - Show infrastructure directory tree"
echo -e "${BLUE}tests-tree${NC} - Show tests directory tree"
echo -e "${BLUE}help${NC}       - Show this help message"
echo ""
echo -e "${YELLOW}Build Examples:${NC}"
echo ""
echo -e "${BLUE}make build${NC}           - Build extension"
echo -e "${BLUE}make build --install${NC} - Build and install extension"
echo -e "${BLUE}make unit${NC}            - Run tests"
echo -e "${BLUE}make fuzz${NC}            - Run canonical fuzz/stress coverage"
echo -e "${BLUE}make stub-parity${NC}     - Check stub/runtime parity after a build"
echo -e "${BLUE}make go-live-readiness${NC} - Run the final local release gate"
echo -e "${BLUE}make release-package${NC} - Build release package under dist/"
echo -e "${BLUE}make release-package-verify${NC} - Verify reproducible release packaging"
echo -e "${BLUE}make clean${NC}           - Clean build"
echo ""
echo -e "${YELLOW}Manual Build Steps:${NC}"
echo ""
echo -e "${BLUE}1.${NC} Initialize submodules:"
echo "   git submodule update --init --recursive"
echo ""
echo -e "${BLUE}2.${NC} Build dependencies:"
echo "   cd quiche && cargo build --release --features ffi,pkg-config-meta,qlog"
echo "   cd libcurl && ./buildconf && ./configure && make"
echo ""
echo -e "${BLUE}3.${NC} Build extension:"
echo "   cd extension && phpize && ./configure --with-king && make"
echo ""
echo -e "${BLUE}4.${NC} Install extension:"
echo "   cd extension && make install"
echo ""
echo -e "${YELLOW}Configuration:${NC}"
echo ""
echo "Add to php.ini:"
echo "extension=king.so"
echo ""
echo -e "${YELLOW}Testing:${NC}"
echo ""
echo "php -m | grep king"
echo "php -r \"echo king_version();\""
