export const CALL_STATE_SIGNAL_TYPES = Object.freeze([
  'call/control-state',
  'call/media-quality-pressure',
  'call/moderation-state',
]);

export const ACTIVITY_PUBLISH_INTERVAL_MS = 800;
export const ACTIVITY_MOTION_SAMPLE_MS = 500;
export const SFU_SELECTIVE_TILE_PATCH_ENABLED = true;
export const SFU_SELECTIVE_TILE_WIDTH = 96;
export const SFU_SELECTIVE_TILE_HEIGHT = 96;
export const SFU_SELECTIVE_TILE_SAMPLE_STRIDE = 8;
export const SFU_SELECTIVE_TILE_DIFF_THRESHOLD = 42;
export const SFU_SELECTIVE_TILE_MAX_CHANGED_RATIO = 0.34;
export const SFU_SELECTIVE_TILE_MAX_PATCH_AREA_RATIO = 0.48;
export const SFU_SELECTIVE_TILE_BASE_REFRESH_MS = 2500;
export const SFU_BACKGROUND_SNAPSHOT_ENABLED = true;
export const SFU_BACKGROUND_SNAPSHOT_TILE_WIDTH = 128;
export const SFU_BACKGROUND_SNAPSHOT_TILE_HEIGHT = 128;
export const SFU_BACKGROUND_SNAPSHOT_SAMPLE_STRIDE = 12;
export const SFU_BACKGROUND_SNAPSHOT_DIFF_THRESHOLD = 28;
export const SFU_BACKGROUND_SNAPSHOT_MIN_CHANGED_RATIO = 0.18;
export const SFU_BACKGROUND_SNAPSHOT_MAX_CHANGED_RATIO = 0.75;
export const SFU_BACKGROUND_SNAPSHOT_MAX_PATCH_AREA_RATIO = 0.92;
export const SFU_BACKGROUND_SNAPSHOT_MIN_INTERVAL_MS = 3500;
export const REMOTE_FRAME_ACTIVITY_MARK_INTERVAL_MS = 1000;
export const REMOTE_VIDEO_STALL_THRESHOLD_MS = 3000;
export const REMOTE_VIDEO_FREEZE_THRESHOLD_MS = 2000;
export const REMOTE_VIDEO_STALL_CHECK_INTERVAL_MS = 1000;
export const REMOTE_VIDEO_KEYFRAME_WAIT_LOG_COOLDOWN_MS = 3000;
export const REMOTE_SFU_FRAME_STALE_TTL_MS = 5000;
export const REMOTE_SFU_FRAME_DROP_LOG_COOLDOWN_MS = 2500;
export const MEDIA_SECURITY_HANDSHAKE_RETRY_TIMEOUTS_MS = Object.freeze([1000, 3000, 6000]);
export const MEDIA_SECURITY_HANDSHAKE_TIMEOUT_MS = MEDIA_SECURITY_HANDSHAKE_RETRY_TIMEOUTS_MS[MEDIA_SECURITY_HANDSHAKE_RETRY_TIMEOUTS_MS.length - 1];
export const MEDIA_SECURITY_HANDSHAKE_WATCHDOG_INTERVAL_MS = 1000;
export const MEDIA_SECURITY_SFU_TARGET_SETTLE_MS = 50;
export const SFU_AUTO_QUALITY_DOWNGRADE_COOLDOWN_MS = 2500;
export const SFU_AUTO_QUALITY_DOWNGRADE_BACKPRESSURE_WINDOW_MS = 1000;
export const SFU_AUTO_QUALITY_DOWNGRADE_SKIP_THRESHOLD = 2;
export const SFU_AUTO_QUALITY_DOWNGRADE_SEND_FAILURE_THRESHOLD = 2;
export const SFU_AUTO_QUALITY_RECOVERY_STABLE_WINDOW_MS = 15_000;
export const SFU_AUTO_QUALITY_RECOVERY_MIN_INTERVAL_MS = 30_000;
export const SFU_AUTO_QUALITY_RECOVERY_MAX_READBACK_BUDGET_RATIO = 0.6;
export const SFU_WLVC_MOTION_DELTA_CADENCE_WINDOW_MS = 9_000;
export const SFU_WLVC_MOTION_DELTA_PROFILE_DOWNSHIFT_THRESHOLD = 3;
export const SFU_WLVC_MOTION_DELTA_MAX_CADENCE_LEVEL = 3;
export const SFU_WLVC_MOTION_DELTA_STABLE_WINDOW_MS = 6_000;
export const SFU_WLVC_MOTION_DELTA_STABLE_SAMPLE_COUNT = 4;
export const SFU_VIDEO_RECOVERY_RECONNECT_COOLDOWN_MS = 5000;
export const SFU_BACKPRESSURE_LOG_COOLDOWN_MS = 3000;
export const SFU_WLVC_MAX_DELTA_FRAME_BYTES = 5632 * 1024;
export const SFU_WLVC_MAX_KEYFRAME_FRAME_BYTES = 6656 * 1024;
export const SFU_AUTO_QUALITY_DOWNGRADE_NEXT = Object.freeze({
  quality: 'balanced',
  balanced: 'realtime',
  realtime: 'rescue',
});
export const SFU_AUTO_QUALITY_RECOVERY_NEXT = Object.freeze({
  rescue: 'realtime',
  realtime: 'balanced',
  balanced: '',
});
export const NATIVE_FRAME_ERROR_LOG_COOLDOWN_MS = 2500;
export const NATIVE_AUDIO_TRACK_RECOVERY_MAX_ATTEMPTS = 2;
export const NATIVE_AUDIO_TRACK_RECOVERY_DELAY_MS = 500;
export const NATIVE_AUDIO_TRACK_RECOVERY_REJOIN_DELAY_MS = 250;
export const SFU_PROTECTED_MEDIA_ENABLED = true;
