/*
 * Client PHP class-entry storage.
 */

zend_class_entry *king_ce_session       = NULL;
zend_class_entry *king_ce_stream        = NULL;
zend_class_entry *king_ce_response      = NULL;
zend_class_entry *king_ce_client_http   = NULL;
zend_class_entry *king_ce_client_http1  = NULL;
zend_class_entry *king_ce_client_http2  = NULL;
zend_class_entry *king_ce_client_http3  = NULL;
zend_class_entry *king_ce_ws_connection = NULL;
zend_class_entry *king_ce_ws_exception         = NULL;
zend_class_entry *king_ce_ws_connection_error  = NULL;
zend_class_entry *king_ce_ws_protocol_error    = NULL;
zend_class_entry *king_ce_ws_timeout           = NULL;
zend_class_entry *king_ce_ws_closed            = NULL;
