function md(lines) {
  return `${lines.join('\n')}\n`;
}

export const INFRASTRUCTURE_PROVIDERS = Object.freeze([
  {
    key: 'codesphere',
    label: 'Codesphere',
    summary: 'PaaS-Workspaces, Replicas, Landscapes und API-Automation fuer schnelle Test- und Preview-Infrastrukturen.',
    markdown: md([
      '# Codesphere',
      '',
      '> Stand: 6. Mai 2026. Fokus: Testaccount bewerten, King Extension ausrollen und Video-Call-Workloads elastisch betreiben.',
      '',
      '## Inhaltsverzeichnis',
      '',
      '- [Einsatzprofil](#einsatzprofil)',
      '- [Ausbauoptionen](#ausbauoptionen)',
      '- [King Extension Rollout](#king-extension-rollout)',
      '- [Autoscaling fuer Video-Calls](#autoscaling-fuer-video-calls)',
      '- [Monitoring mit OpenTelemetry](#monitoring-mit-opentelemetry)',
      '- [E-Mail und DNS](#e-mail-und-dns)',
      '- [Entscheidungspunkte](#entscheidungspunkte)',
      '- [Quellen](#quellen)',
      '',
      '## Einsatzprofil',
      '',
      'Codesphere ist fuer uns interessant, wenn wir schnell reproduzierbare Preview- und Testumgebungen wollen, ohne sofort einen eigenen Kubernetes-Betrieb aufzubauen. Fuer Produktion muss der Workspace-Modus **Always On** sein. Standby ist fuer Call-Join-Ziele ungeeignet, weil ein Workspace zwar schnell startet, die App aber erst ueber die Run-Stage wieder sauber hochfahren muss.',
      '',
      '```mermaid',
      'flowchart LR',
      '  User[Browser / Mobile] --> Domain[app.kingrt.com]',
      '  Domain --> Frontend[Codesphere Frontend Service]',
      '  Frontend --> Api[API Service]',
      '  Frontend --> Ws[WebSocket Service]',
      '  Ws --> Sfu[SFU / Call Runtime]',
      '  Api --> Store[(DB / Object Store)]',
      '  Sfu --> Store',
      '  Api --> OTel[OTel Collector]',
      '  Ws --> OTel',
      '  Sfu --> OTel',
      '```',
      '',
      '## Ausbauoptionen',
      '',
      '| Option | Wofuer | Autoscaling-Potenzial | Risiko |',
      '| --- | --- | --- | --- |',
      '| Single Always-On Workspace | Testaccount, Demo, kleine Staging-Instanz | Vertikal ueber Ressourcenplan, horizontal nur begrenzt sinnvoll | Single Runtime, keine echte SFU-Verteilung |',
      '| Replicas | Stateless HTTP/API-Services | Replicas koennen horizontal via UI/API erhoeht werden | Gemeinsames Filesystem, keine konkurrierenden Writes |',
      '| Landscapes | Mehrere Services im Workspace: Frontend, API, WS, SFU, Worker | Services koennen getrennt dimensioniert werden | Service-Kommunikation muss intern ueber Service-Namen laufen |',
      '| Public API + King Orchestrator | Automatisierte Release-/Scale-Operationen | Grundlage fuer King-gesteuertes Scale-out | API-Funktionen im Testaccount konkret pruefen |',
      '| Externe Stateful Services | DB, Object Store, Queue, Mail | Entkoppelt Replikate von Workspace-Filesystem | Netzwerk, Secrets und Backups sauber trennen |',
      '',
      '## King Extension Rollout',
      '',
      '1. Repository im Codesphere Workspace verbinden.',
      '2. Workspace auf **Always On** setzen, falls die Umgebung Call-Traffic annehmen soll.',
      '3. Env Vars pro Workspace pflegen: `KING_ENV`, `KING_BASE_URL`, `KING_API_URL`, `KING_WS_URL`, `KING_SFU_URL`, `KING_OBJECT_STORE_*`, `SMTP_*`, `OTEL_EXPORTER_OTLP_ENDPOINT`.',
      '4. `ci.yml` mit Prepare, Test und Run pflegen. Die Run-Stage muss pro Service eindeutig starten und auf Crash automatisch neu starten.',
      '5. Landschaft trennen: Frontend, API, WebSocket, SFU und Background Worker als eigene Services definieren.',
      '6. Interne Service-Kommunikation nicht ueber public URLs, sondern ueber Codesphere-private Service-Namen.',
      '7. Logs niemals in eine gemeinsam geschriebene Datei legen. Wenn File-Logs noetig sind, pro Replica mit `CS_REPLICA` trennen.',
      '',
      '```yaml',
      'prepare:',
      '  steps:',
      '    - name: install frontend',
      '      command: cd demo/video-chat/frontend-vue && npm ci && npm run build',
      '    - name: backend sanity',
      '      command: ./demo/video-chat/backend-king-php/tests/smoke.sh',
      'test:',
      '  steps:',
      '    - name: frontend contracts',
      '      command: cd demo/video-chat/frontend-vue && npm run test:contract:client-diagnostics',
      'run:',
      '  steps:',
      '    - name: king api',
      '      command: ./ops/codesphere/run-api.sh',
      '    - name: king ws',
      '      command: ./ops/codesphere/run-ws.sh',
      '    - name: king sfu',
      '      command: ./ops/codesphere/run-sfu.sh',
      '```',
      '',
      '## Autoscaling fuer Video-Calls',
      '',
      '- **Join-Ziel:** Call-Lobby und Signalling muessen warm sein. Always-On ist Pflicht fuer <1s Join-Ziel.',
      '- **Stateless API:** Codesphere Replicas sind geeignet, wenn Sessions zentral validiert und keine lokalen Dateien als Zustand genutzt werden.',
      '- **WebSocket:** Sticky Routing oder zentraler Session-/Presence-Store noetig. Ohne das verteilt ein Replica-Wechsel den Call-Zustand falsch.',
      '- **SFU:** Nicht blind replizieren. Rooms muessen einem SFU-Shard zugewiesen werden; ein King-Orchestrator muss Room-to-SFU-Routing und Draining steuern.',
      '- **Callapps/Workers:** Eignen sich besser fuer horizontale Replicas, wenn Jobs idempotent sind und Queue/Locking extern liegen.',
      '- **Shared Filesystem:** Codesphere-Replicas teilen `/home/user/app`. Runtime-State, Jitter Buffer, Uploads und Logs gehoeren nicht dorthin.',
      '',
      '```mermaid',
      'sequenceDiagram',
      '  participant B as Browser',
      '  participant API as API Replica',
      '  participant ORC as King Orchestrator',
      '  participant SFU as SFU Shard',
      '  participant O as Object Store',
      '  B->>API: Join Call',
      '  API->>ORC: allocate room / capabilities',
      '  ORC->>SFU: reserve room',
      '  SFU-->>ORC: room endpoint',
      '  ORC-->>API: signed routing token',
      '  API-->>B: ws/sfu endpoint',
      '  B->>SFU: publish media',
      '  SFU->>O: diagnostics / snapshots only',
      '```',
      '',
      '## Monitoring mit OpenTelemetry',
      '',
      '- Fuer Codesphere zuerst OTLP direkt an einen externen Collector senden.',
      '- App-Services setzen `OTEL_EXPORTER_OTLP_ENDPOINT`, `OTEL_SERVICE_NAME`, `OTEL_RESOURCE_ATTRIBUTES`.',
      '- Pro Service getrennte Namen verwenden: `king-api`, `king-ws`, `king-sfu`, `king-callapp-worker`.',
      '- Wenn Landscapes stabil laufen, kann ein OTel Collector als interner Service laufen und an Grafana/Tempo/Loki/Prometheus Remote Write exportieren.',
      '',
      '## E-Mail und DNS',
      '',
      '- SMTP nicht lokal betreiben. Codesphere Workspaces sollten nur gegen externen SMTP/Transactional-Mail-Provider senden.',
      '- Secrets in Env Vars speichern: `SMTP_HOST`, `SMTP_PORT`, `SMTP_USER`, `SMTP_PASSWORD`, `MAIL_FROM`, `MAIL_REPLY_TO`.',
      '- DNS fuer Produktivdomains: App/API/WS/SFU/CDN getrennt halten.',
      '- Versanddomain mit SPF, DKIM und DMARC pruefen, sonst landen Booking- und Lead-Mails im Spam.',
      '',
      '## Entscheidungspunkte',
      '',
      '- Kann der Testaccount Landscapes nutzen?',
      '- Gibt es API-Zugriff auf Replicas/Ressourcenplaene fuer Autoscaling?',
      '- Wie werden Custom Domains und Pfad-Routing im Account freigeschaltet?',
      '- Welche Grenzen gelten fuer CPU, RAM, Storage, Replicas und offene WebSocket-Verbindungen?',
      '- Koennen SFU-Ports und lange WebSocket-Verbindungen stabil betrieben werden?',
      '',
      '## Quellen',
      '',
      '- [Codesphere Docs](https://docs.codesphere.com/)',
      '- [Codesphere API Swagger](https://codesphere.com/api/swagger-ui)',
      '- [Codesphere CI Pipelines](https://codesphere.com/articles/ci-pipelines)',
      '- [Codesphere Deployment Modes](https://codesphere.com/articles/deployment-modes)',
      '- [Codesphere Horizontal Scaling with Replicas](https://codesphere.com/articles/horizontal-scaling-with-replicas)',
      '- [Codesphere Landscapes](https://codesphere.com/articles/deploy-landscapes)',
      '- [Codesphere Technology: Scaling, Observability, Infrastructure](https://www.codesphere.com/technology)',
      '- [Codesphere Environment Variables](https://codesphere.com/articles/environment-variables)',
      '- [Codesphere Public API](https://codesphere.com/articles/public-api)',
    ]),
  },
  {
    key: 'hetzner',
    label: 'Hetzner',
    summary: 'Cloud API, Load Balancer, Server, Netzwerk, Volumes und selbst verwaltetes Kubernetes fuer maximale Kontrolle.',
    markdown: md([
      '# Hetzner',
      '',
      '## Inhaltsverzeichnis',
      '',
      '- [Einsatzprofil](#einsatzprofil)',
      '- [Ausbauoptionen](#ausbauoptionen)',
      '- [King Extension Rollout](#king-extension-rollout)',
      '- [Autoscaling-Modell](#autoscaling-modell)',
      '- [Monitoring mit OpenTelemetry](#monitoring-mit-opentelemetry)',
      '- [E-Mail und DNS](#e-mail-und-dns)',
      '- [Quellen](#quellen)',
      '',
      '## Einsatzprofil',
      '',
      'Hetzner ist der direkte Infrastructure-as-a-Service-Pfad. Wir bekommen API-gesteuerte Server, Load Balancer, Networks, Firewalls, Floating IPs und Volumes. Damit ist Hetzner fuer King die beste Option, wenn wir Autoscaling wirklich selbst kontrollieren wollen.',
      '',
      '```mermaid',
      'flowchart TB',
      '  Internet --> LB[Hetzner Load Balancer]',
      '  LB --> FE[Frontend/API Pool]',
      '  LB --> WS[WebSocket Pool]',
      '  LB --> SFU[SFU Pool]',
      '  FE --> DB[(Postgres / Redis)]',
      '  WS --> Redis[(Presence / Session Store)]',
      '  SFU --> Obj[(Object Store)]',
      '  ORC[King Orchestrator] --> HCLOUD[Hetzner Cloud API]',
      '  HCLOUD --> FE',
      '  HCLOUD --> WS',
      '  HCLOUD --> SFU',
      '```',
      '',
      '## Ausbauoptionen',
      '',
      '| Option | Wofuer | Autoscaling | Empfehlung |',
      '| --- | --- | --- | --- |',
      '| Einzelner Cloud Server + Docker Compose | schneller Pilot | manuell/API-basiert | nur Dev/Staging |',
      '| 2-3 Server + Hetzner Load Balancer | HA fuer Frontend/API/WS | King-Orchestrator skaliert Servergruppen ueber API | gute Zwischenstufe |',
      '| k3s/Talos/Kubernetes auf Hetzner | Pod-HPA, KEDA, Node Scaling | stark, aber Betrieb liegt bei uns | Zielbild fuer Video-Call-Skalierung |',
      '| Dedicated Root Server + Cloud LB | feste Performance fuer SFU | manuell oder King-Orchestrator | gut fuer planbare SFU-Kapazitaet |',
      '| Hybrid: Codesphere Preview, Hetzner Prod | schnelle Preview + kontrollierte Prod | Preview separat, Prod API-gesteuert | pragmatisch |',
      '',
      '## King Extension Rollout',
      '',
      '1. Basis-Images fuer `king-api`, `king-ws`, `king-sfu`, `king-worker` bauen.',
      '2. Server mit Labels provisionieren: `role=api`, `role=ws`, `role=sfu`, `env=prod`.',
      '3. Private Network fuer API/WS/SFU/DB nutzen; nur Load Balancer oeffentlich.',
      '4. Firewall: nur 80/443 oeffentlich, SSH nur Admin-IP/VPN, interne Ports nur im privaten Netz.',
      '5. King Extension als systemd Service oder Kubernetes Deployment ausrollen.',
      '6. SFU Shards mit Kapazitaetsmetriken registrieren: CPU, RAM, aktive Rooms, Publish-FPS, Recovery-Rate.',
      '7. Draining einbauen: neue Rooms nicht mehr zuweisen, bestehende Calls auslaufen lassen, dann Node entfernen.',
      '',
      '## Autoscaling-Modell',
      '',
      '- **Pod-Level:** Kubernetes HPA fuer API/WS/Worker, KEDA fuer Queue- oder Event-getriebene Worker.',
      '- **Node-Level:** Cluster Autoscaler oder King-Orchestrator ueber Hetzner Cloud API.',
      '- **SFU-Level:** eigenes Signal wichtiger als CPU: aktive Publisher, ausgehende Streams, Encoder-Pressure, Recovery-Routes, RTT und Paketverlust.',
      '- **Callapps:** als Worker Pool skalieren; Jobs muessen idempotent sein.',
      '- **Object Store:** Uploads, Avatare, Background Images und Artefakte nicht auf lokalen Disks halten.',
      '',
      '```mermaid',
      'stateDiagram-v2',
      '  [*] --> WarmPool',
      '  WarmPool --> ScaleOut: rooms > threshold or recovery pressure',
      '  ScaleOut --> RegisterNode: hcloud create server',
      '  RegisterNode --> AcceptRooms: health + otel ready',
      '  AcceptRooms --> Drain: low demand or maintenance',
      '  Drain --> DeleteNode: active rooms = 0',
      '  DeleteNode --> WarmPool',
      '```',
      '',
      '## Monitoring mit OpenTelemetry',
      '',
      '- Kubernetes: OTel Collector als DaemonSet fuer Node-/Pod-Logs und als Deployment fuer Cluster-Metriken.',
      '- VM/Compose: OTel Collector pro Node als systemd Service oder Container.',
      '- Pflichtmetriken: `call.join.latency`, `sfu.publisher.count`, `sfu.recovery.routes`, `ws.session.reconnects`, `object_store.upload.duration`, `mail.send.duration`.',
      '- Exportziel: zunaechst externer OTLP Collector; spaeter eigener Observability Stack.',
      '',
      '## E-Mail und DNS',
      '',
      '- Transaktionsmail via externem SMTP oder dediziertem Mailservice.',
      '- SPF, DKIM und DMARC auf Versanddomain setzen.',
      '- DNS sauber splitten: `app`, `api`, `ws`, `sfu`, `cdn`, `otel`.',
      '- Fuer SFU keine zufaelligen Ports oeffentlich machen; ueber definierte TLS/WebSocket-Endpunkte routen.',
      '',
      '## Quellen',
      '',
      '- [Hetzner Cloud API Overview](https://docs.hetzner.cloud/)',
      '- [Hetzner Load Balancers](https://docs.hetzner.com/networking/load-balancers/overview/)',
      '- [Hetzner Cloud API: Using the API](https://docs.hetzner.com/cloud/api/getting-started/using-api/)',
      '- [Hetzner Cloud Controller Manager](https://github.com/hetznercloud/hcloud-cloud-controller-manager)',
      '- [Kubernetes Autoscaling](https://kubernetes.io/docs/concepts/workloads/autoscaling/)',
      '- [Kubernetes Node Autoscaling](https://kubernetes.io/docs/concepts/cluster-administration/node-autoscaling/)',
    ]),
  },
  {
    key: 'intares',
    label: 'Intares',
    summary: 'Managed Hosting, isolierte Server, Docker/Private-Cloud als individueller Betreiberpfad mit SLA-Klaerung.',
    markdown: md([
      '# Intares',
      '',
      '## Inhaltsverzeichnis',
      '',
      '- [Einsatzprofil](#einsatzprofil)',
      '- [Ausbauoptionen](#ausbauoptionen)',
      '- [King Extension Rollout](#king-extension-rollout)',
      '- [Autoscaling-Realitaet](#autoscaling-realitaet)',
      '- [Monitoring mit OpenTelemetry](#monitoring-mit-opentelemetry)',
      '- [E-Mail und DNS](#e-mail-und-dns)',
      '- [Fragen an Intares](#fragen-an-intares)',
      '- [Quellen](#quellen)',
      '',
      '## Einsatzprofil',
      '',
      'Intares wirkt nach aktueller oeffentlicher Doku wie ein Managed-Hosting-/Managed-Server-Partner mit isolierten Servern, Backup, Management und optional Docker/Private-Cloud-Setups. Das ist gut fuer betreute, dedizierte Infrastruktur. Ein Self-Service-API-Autoscaling wie bei Hetzner oder eine PaaS-Replica-Schicht wie bei Codesphere ist oeffentlich nicht belastbar dokumentiert.',
      '',
      '```mermaid',
      'flowchart LR',
      '  King[King Platform Team] --> Runbook[Runbook + Release Bundle]',
      '  Runbook --> Intares[Intares Managed Ops]',
      '  Intares --> Nodes[Managed Server / Private Cloud]',
      '  Nodes --> Apps[King API / WS / SFU / Worker]',
      '  Apps --> Observability[OTel + Alerts]',
      '  Observability --> King',
      '```',
      '',
      '## Ausbauoptionen',
      '',
      '| Option | Wofuer | Autoscaling | Risiko |',
      '| --- | --- | --- | --- |',
      '| Managed Einzelserver | kleiner produktiver Start | vertikal/manuell | keine elastische Call-Spitze |',
      '| Managed HA-Paar | API/Website mit Failover | manuell nach Runbook | SFU-Routing muss geklaert werden |',
      '| Docker auf Managed Servern | reproduzierbare King Services | Skript/API nur falls freigegeben | Betreibergrenzen klaeren |',
      '| Private Cloud Service | kundenspezifisches Cluster | moeglich, aber Vertrags-/Betriebsfrage | keine Annahmen ohne Angebot |',
      '| Intares + Hetzner/Codesphere Hybrid | Managed DB/Security + elastische App-Worker woanders | King-Orchestrator extern | Netzwerk/DSGVO sauber dokumentieren |',
      '',
      '## King Extension Rollout',
      '',
      '1. Intares bekommt ein versioniertes Release-Bundle oder Container Images aus unserer Registry.',
      '2. Wir liefern systemd-Units oder Compose/Kubernetes-Manifeste fuer API, WS, SFU und Worker.',
      '3. Secrets werden nicht im Bundle geliefert, sondern im Intares Secret-/Server-Setup gesetzt.',
      '4. Healthchecks muessen von Intares-Monitoring und King-Orchestrator getrennt erreichbar sein.',
      '5. Backups: DB konsistent sichern, Object Store versioniert, lokale Runtime-Puffer nicht sichern.',
      '6. Rollback: altes Image/Bundle behalten, Datenbankmigrationen vorab mit Down-Strategie bewerten.',
      '',
      '## Autoscaling-Realitaet',
      '',
      '- Ohne dokumentierte Self-Service-API planen wir Intares nicht als automatisches Scale-out-Ziel.',
      '- Fuer Video-Call-Spitzen brauchen wir mindestens ein Warm-Pool-Konzept oder garantierte Betreiber-Reaktionszeiten.',
      '- SFU-Skalierung muss als Capacity Pool geplant werden: feste Shards plus manuelles oder vertraglich automatisiertes Nachprovisionieren.',
      '- Wenn Intares Kubernetes/Private Cloud bereitstellt, gelten die Kubernetes-Regeln: HPA/KEDA fuer Workloads, Node Scaling nur mit Provider-Integration.',
      '',
      '```mermaid',
      'sequenceDiagram',
      '  participant K as King Orchestrator',
      '  participant M as Monitoring',
      '  participant I as Intares Ops',
      '  participant N as Managed Node',
      '  M->>K: capacity pressure',
      '  K->>I: scale request / ticket / API if available',
      '  I->>N: provision or resize',
      '  N-->>K: health ready',
      '  K->>N: assign new rooms',
      '```',
      '',
      '## Monitoring mit OpenTelemetry',
      '',
      '- OTel Collector als systemd Service oder Container auf jedem Host.',
      '- Intares Monitoring darf parallel laufen, aber King braucht eigene OTLP-Daten fuer Call-spezifische Skalierung.',
      '- Alerts an beide Seiten: Betreiber fuer Host/Netz/Disk, King-Team fuer Call-Metriken und App-Fehler.',
      '',
      '## E-Mail und DNS',
      '',
      '- Wenn Intares Mail betreibt: SPF/DKIM/DMARC und Bounce Handling schriftlich klaeren.',
      '- Wenn externer SMTP genutzt wird: Credentials als Managed Secret, Versanddomain bei uns dokumentieren.',
      '- DNS-Zonen und Zertifikatsverantwortung vor Rollout festlegen.',
      '',
      '## Fragen an Intares',
      '',
      '- Gibt es eine API fuer Server/Firewall/LB/DNS/Scale-Operationen?',
      '- Wird Docker Compose, Kubernetes oder eine Private-Cloud-Orchestrierung angeboten?',
      '- Wie werden Rolling Deployments und Rollbacks betrieben?',
      '- Welche SLA gilt fuer kurzfristiges Nachskalieren?',
      '- Koennen wir OTel Collector, Prometheus Exporter und eigene Healthchecks betreiben?',
      '- Wie werden WebSocket- und SFU-Langverbindungen am Load Balancer behandelt?',
      '',
      '## Quellen',
      '',
      '- [Intares Managed Hosting](https://www.intares.de/)',
      '- [Intares Full Managed Hosting / Docker / Private Cloud](https://www.intares.de/full-managed-hosting-green-it/)',
      '- [Kubernetes Autoscaling](https://kubernetes.io/docs/concepts/workloads/autoscaling/)',
      '- [OpenTelemetry Collector auf Kubernetes](https://opentelemetry.io/docs/platforms/kubernetes/getting-started/)',
    ]),
  },
  {
    key: 'mittwald',
    label: 'mittwald',
    summary: 'Managed Container Hosting mit mStudio, CLI, API und Terraform; gut fuer App-Services, begrenzt fuer SFU-Autoscaling.',
    markdown: md([
      '# mittwald',
      '',
      '## Inhaltsverzeichnis',
      '',
      '- [Einsatzprofil](#einsatzprofil)',
      '- [Ausbauoptionen](#ausbauoptionen)',
      '- [King Extension Rollout](#king-extension-rollout)',
      '- [Autoscaling-Einschaetzung](#autoscaling-einschaetzung)',
      '- [Monitoring mit OpenTelemetry](#monitoring-mit-opentelemetry)',
      '- [E-Mail und DNS](#e-mail-und-dns)',
      '- [Quellen](#quellen)',
      '',
      '## Einsatzprofil',
      '',
      'mittwald bietet Container Hosting im mStudio mit UI, CLI, API und Terraform. Container koennen aus Registries gestartet, als Stack deployed, mit Env Vars, Volumes und Ports konfiguriert und per Domain/Ingress erreichbar gemacht werden. Das ist stark fuer Website, API, Worker und kleinere Services. Fuer harte SFU-Autoscaling-Ziele muessen wir pruefen, ob Ressourcen/Instanzen automatisch genug steuerbar sind.',
      '',
      '```mermaid',
      'flowchart TB',
      '  Registry[Image Registry] --> MW[mStudio / CLI / Terraform]',
      '  MW --> Stack[Container Stack]',
      '  Stack --> Frontend[Frontend Container]',
      '  Stack --> Api[API Container]',
      '  Stack --> Worker[Worker Container]',
      '  Stack --> Collector[OTel Collector Container]',
      '  Domain[Domain / Ingress] --> Frontend',
      '  Frontend --> Api',
      '  Api --> Worker',
      '```',
      '',
      '## Ausbauoptionen',
      '',
      '| Option | Wofuer | Autoscaling | Empfehlung |',
      '| --- | --- | --- | --- |',
      '| mStudio Container | manuelle Einrichtung, schnelle Tests | manuell | guter Einstieg |',
      '| `mw container run` | skriptbare Deployments | skriptbar | fuer Runbooks |',
      '| `mw stack deploy` | Compose-kompatible Stacks | stack-basiert | gut fuer API/Worker |',
      '| Terraform Provider | versionierte Infrastruktur | planbar, reviewbar | bevorzugt fuer reproduzierbare Umgebungen |',
      '| API Image Update | Rolling Release/Mutable Tag Pull | automatisierbar | fuer CI/CD sinnvoll |',
      '',
      '## King Extension Rollout',
      '',
      '1. Container Images fuer King Services bauen und in GitHub/GitLab/DockerHub/private Registry pushen.',
      '2. mittwald Container Stack definieren: API, WS, Worker, optional Collector.',
      '3. Public Ingress nur fuer Frontend/API/WS; interne Services ueber interne DNS-Namen verbinden.',
      '4. Volumes nur fuer explizit persistente Daten nutzen. Runtime-Puffer und Jitter Buffer bleiben im RAM.',
      '5. Image Tags immutable deployen: `king-api:1.0.8`, `king-ws:1.0.8`, `king-worker:1.0.8`.',
      '6. Release per `mw container update --image ...` oder Terraform Variable `image_tag` ausrollen.',
      '',
      '```bash',
      'mw container run \\',
      '  --name king-api \\',
      '  --env KING_ENV=production \\',
      '  --env OTEL_EXPORTER_OTLP_ENDPOINT=https://otel.example.com \\',
      '  -p 8080:8080/tcp \\',
      '  registry.example.com/king-api:1.0.8',
      '```',
      '',
      '## Autoscaling-Einschaetzung',
      '',
      '- API und Worker koennen gut containerisiert werden.',
      '- Fuer Video-SFU muessen wir Langverbindungen, CPU-Reservierung, Port-/Ingress-Verhalten und horizontale Instanzsteuerung testen.',
      '- Ohne dokumentierte native Autoscaling-Funktion planen wir mittwald als Managed Container Ziel mit kontrolliertem Scaling per API/Terraform, nicht als vollautomatischen SFU-Autoscaler.',
      '- Callapps koennen ueber mehrere Worker-Container laufen, wenn Queue/Locks extern liegen.',
      '',
      '## Monitoring mit OpenTelemetry',
      '',
      '- OTel Export direkt aus jedem Container an externen Collector.',
      '- Alternativ Collector als eigener Container im Stack, falls interne Erreichbarkeit stabil ist.',
      '- Logs weiter im mStudio sichtbar lassen, aber nicht als einzige Diagnosequelle nutzen.',
      '',
      '## E-Mail und DNS',
      '',
      '- Mailversand ueber externen SMTP/Transactional Provider oder mittwald-Mail nur nach Zustellbarkeitscheck.',
      '- SPF/DKIM/DMARC fuer Versanddomain konfigurieren.',
      '- Public Domains im mStudio auf Container/Ingress legen: `app`, `api`, `ws`, optional `cdn`.',
      '',
      '## Quellen',
      '',
      '- [mittwald Developer Portal: Containerized Applications](https://developer.mittwald.de/docs/v2/platform/workloads/containers/)',
      '- [mittwald Container Hosting](https://www.mittwald.de/mstudio/container-hosting)',
      '- [mittwald Blog: Container Workflows](https://www.mittwald.de/blog/webentwicklung-design/container-bei-mittwald-starten-fuenf-unterschiedliche-workflows)',
      '- [OpenTelemetry Collector auf Kubernetes](https://opentelemetry.io/docs/platforms/kubernetes/getting-started/)',
      '- [OpenTelemetry OTLP Exporter](https://opentelemetry.io/docs/specs/otel/protocol/exporter/)',
    ]),
  },
]);

export const DEFAULT_INFRASTRUCTURE_PROVIDER = 'codesphere';
